spring:
  # h2 ?? ??
  h2:
    console:
      enabled: true #h2 ?? ?? ??
      path: /h2-console  #?? ??
  # database ?? ??
  datasource:
    driver-class-name: org.h2.Driver  #h2 ??
    url: jdbc:h2:~/test  # h2 ?? ??
    username: test  # ??? ? username
    password: test1234 # ??? ? password
